page_title = "Vendors Directory"
page_max_width_px = 99999
sidebar_state = "collapsed"

# Column labels — start simple; you can change anytime
READONLY_COLUMN_LABELS = { business_name = "Provider" }
ADMIN_COLUMN_LABELS    = { business_name = "Provider" }

# Admin password gate
ADMIN_PASSWORD = "CHANGE-THIS-TO-A-STRONG-PASSWORD"

# Turso (libSQL) remote DB
TURSO_DATABASE_URL = "sqlite+libsql://<your>.turso.io?secure=true"
TURSO_AUTH_TOKEN   = "<your_long_jwt>"
